"""auto migration

Revision ID: 2211d432885a
Revises: 
Create Date: 2026-05-31 21:07:04.118788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2211d432885a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reading_sessions_book_id_fkey'), 'reading_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'reading_sessions', 'books', ['book_id'], ['id'], source_schema='books', referent_schema='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_sessions', schema='books', type_='foreignkey')
    op.create_foreign_key(op.f('reading_sessions_book_id_fkey'), 'reading_sessions', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
