"""autogenerated migration

Revision ID: 5350cf332ceb
Revises: 9b942dcb8538
Create Date: 2026-05-31 10:32:47.152943

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5350cf332ceb"
down_revision: str | Sequence[str] | None = "9b942dcb8538"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("minutes_read", sa.Integer(), nullable=False),
        sa.Column("pages_read", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="books",
    )
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_index(op.f("ix_books_created_at"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_index(op.f("ix_books_status"), table_name="books")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.create_index(op.f("ix_books_books_author"), "books", ["author"], unique=False, schema="books")
    op.create_index(op.f("ix_books_books_created_at"), "books", ["created_at"], unique=False, schema="books")
    op.create_index(op.f("ix_books_books_id"), "books", ["id"], unique=False, schema="books")
    op.create_index(op.f("ix_books_books_status"), "books", ["status"], unique=False, schema="books")
    op.create_index(op.f("ix_books_books_title"), "books", ["title"], unique=True, schema="books")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_books_title"), table_name="books", schema="books")
    op.drop_index(op.f("ix_books_books_status"), table_name="books", schema="books")
    op.drop_index(op.f("ix_books_books_id"), table_name="books", schema="books")
    op.drop_index(op.f("ix_books_books_created_at"), table_name="books", schema="books")
    op.drop_index(op.f("ix_books_books_author"), table_name="books", schema="books")
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=True)
    op.create_index(op.f("ix_books_status"), "books", ["status"], unique=False)
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_created_at"), "books", ["created_at"], unique=False)
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.drop_table("reading_sessions", schema="books")
    # ### end Alembic commands ###
