"""auto migration

Revision ID: 62f8c8b8446b
Revises: 
Create Date: 2026-06-01 20:52:05.877337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f8c8b8446b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('alternative_title', sa.String(length=255), nullable=True),
    sa.Column('studio', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AIRING', 'COMPLETED', 'UPCOMING', name='animestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    schema='books'
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('READ', 'PENDING', 'READING', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='books'
    )
    op.create_index(op.f('ix_books_books_author'), 'books', ['author'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_created_at'), 'books', ['created_at'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_id'), 'books', ['id'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_status'), 'books', ['status'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_title'), 'books', ['title'], unique=True, schema='books')
    op.create_table('anime_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.CheckConstraint('season_number > 0', name='ck_season_number_positive'),
    sa.ForeignKeyConstraint(['anime_id'], ['books.anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'season_number', name='uq_anime_season'),
    schema='books'
    )
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('minutes_read', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='books'
    )
    op.create_table('watch_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('watch_status', sa.Enum('WATCHING', 'COMPLETED', 'ON_HOLD', 'DROPPED', 'PLAN_TO_WATCH', name='watchstatus'), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('current_episode >= 0', name='ck_current_episode_positive'),
    sa.ForeignKeyConstraint(['season_id'], ['books.anime_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='books'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_entries', schema='books')
    op.drop_table('reading_sessions', schema='books')
    op.drop_table('anime_seasons', schema='books')
    op.drop_index(op.f('ix_books_books_title'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_status'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_id'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_created_at'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_author'), table_name='books', schema='books')
    op.drop_table('books', schema='books')
    op.drop_table('anime', schema='books')
    # ### end Alembic commands ###
