"""auto migration~

Revision ID: d4da9de2f0a9
Revises: 
Create Date: 2026-06-28 22:18:26.860917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4da9de2f0a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('alternative_title', sa.String(length=255), nullable=True),
    sa.Column('studio', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('airing', 'completed', 'upcoming', name='anime_status_enum', schema='anime'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    schema='anime'
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('read', 'pending', 'reading', name='books_status_enum', schema='books'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='books'
    )
    op.create_index(op.f('ix_books_books_author'), 'books', ['author'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_created_at'), 'books', ['created_at'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_id'), 'books', ['id'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_status'), 'books', ['status'], unique=False, schema='books')
    op.create_index(op.f('ix_books_books_title'), 'books', ['title'], unique=True, schema='books')
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='openweather'
    )
    op.create_table('current_weather_json',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('dt', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.Column('cod', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', name='uq_current_weather_json_city'),
    schema='openweather'
    )
    op.create_index('ix_current_weather_json_dt', 'current_weather_json', ['dt'], unique=False, schema='openweather')
    op.create_table('anime_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.CheckConstraint('season_number > 0', name='ck_season_number_positive'),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'season_number', name='uq_anime_season'),
    schema='anime'
    )
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('minutes_read', sa.Integer(), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='books'
    )
    op.create_table('city_astronomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.BigInteger(), nullable=False),
    sa.Column('sunset', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['openweather.cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'date', name='uq_astronomy_city_date'),
    schema='openweather'
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.BigInteger(), nullable=False),
    sa.Column('dt_txt', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['openweather.cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'dt', name='uq_forecast_city_dt'),
    schema='openweather'
    )
    op.create_table('watch_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('watch_status', sa.Enum('watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch', name='anime_watch_status_enum', schema='anime'), nullable=False),
    sa.Column('current_episode', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('current_episode >= 0', name='ck_current_episode_positive'),
    sa.ForeignKeyConstraint(['season_id'], ['anime.anime_seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='anime'
    )
    op.create_table('forecast_clouds',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('all', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='openweather'
    )
    op.create_table('forecast_main',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('sea_level', sa.Integer(), nullable=True),
    sa.Column('grnd_level', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temp_kf', sa.Float(), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='openweather'
    )
    op.create_table('forecast_rain',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('volume_3h', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='openweather'
    )
    op.create_table('forecast_sys',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('pod', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='openweather'
    )
    op.create_table('forecast_wind',
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('deg', sa.Integer(), nullable=True),
    sa.Column('gust', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    schema='openweather'
    )
    op.create_table('weather_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.Column('main', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['openweather.forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='openweather'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_conditions', schema='openweather')
    op.drop_table('forecast_wind', schema='openweather')
    op.drop_table('forecast_sys', schema='openweather')
    op.drop_table('forecast_rain', schema='openweather')
    op.drop_table('forecast_main', schema='openweather')
    op.drop_table('forecast_clouds', schema='openweather')
    op.drop_table('watch_entries', schema='anime')
    op.drop_table('forecasts', schema='openweather')
    op.drop_table('city_astronomy', schema='openweather')
    op.drop_table('reading_sessions', schema='books')
    op.drop_table('anime_seasons', schema='anime')
    op.drop_index('ix_current_weather_json_dt', table_name='current_weather_json', schema='openweather')
    op.drop_table('current_weather_json', schema='openweather')
    op.drop_table('cities', schema='openweather')
    op.drop_index(op.f('ix_books_books_title'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_status'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_id'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_created_at'), table_name='books', schema='books')
    op.drop_index(op.f('ix_books_books_author'), table_name='books', schema='books')
    op.drop_table('books', schema='books')
    op.drop_table('anime', schema='anime')
    # ### end Alembic commands ###
