DROP VIEW IF EXISTS OPENWEATHER.VW_CURRENT_DAY_DETAILS;
CREATE VIEW OPENWEATHER.VW_CURRENT_DAY_DETAILS AS (
	SELECT DISTINCT
		ON (C.ID) FM.TEMP,
        C.NAME as CITY_NAME,
		FM.FEELS_LIKE,
		FM.TEMP_MIN,
		FM.TEMP_MAX,
		FM.PRESSURE,
		FM.SEA_LEVEL,
		FM.HUMIDITY,
		FW.SPEED AS WIND_SPEED,
		FW.DEG AS WIND_DIRECTION,
		FW.GUST AS WIND_GUST,
		WC.DESCRIPTION AS WEATHER_DESCRIPTION
	FROM
		OPENWEATHER.FORECASTS F
		JOIN OPENWEATHER.CITIES C ON C.ID = F.CITY_ID
		LEFT JOIN OPENWEATHER.FORECAST_MAIN FM ON FM.FORECAST_ID = F.ID
		LEFT JOIN OPENWEATHER.FORECAST_WIND FW ON FW.FORECAST_ID = F.ID
		LEFT JOIN OPENWEATHER.WEATHER_CONDITIONS WC ON WC.FORECAST_ID = F.ID
	WHERE
		DATE (F.DT_TXT) = CURRENT_DATE
	ORDER BY
		C.ID,
		F.DT_TXT
);

-- SELECT
-- 	*
-- FROM
-- 	OPENWEATHER.VW_CURRENT_DAY_DETAILS;
